site_name: Agile Methodology Guide
site_description: Comprehensive guide to agile methodology and practices
site_author: Alex
site_url: https://alex.github.io/agile

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Fundamentals:
    - Introduction: fundamentals/introduction.md
    - Agile Principles: fundamentals/principles.md
    - Scrum Framework: fundamentals/scrum-framework.md
    - Agile vs DevOps: fundamentals/agile-vs-devops.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
